app:
  name: My App
  description: Welcome to ${app.name}

my:
  greeting: Hello World Test
  list:
    values: One,Two,Three

dbValues: "{connectionString: 'http://___', userName: 'foo', password: 'pass'}"

db:
  connection: test-connection-string-here
  host: 127.0.0.1
  port: 2400

# Not use for production! It's expose sensitive data
management.endpoints.web.exposure.include: "*"